version: "2"

services:
  api:
    image: cshr/api
    build:
      context: .
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
