version: "2"

services:
  api:
    ports:
      - "8080:8080"
    networks:
      - cshr-net

  db:
    ports:
      - "5432:5432"
    networks:
      - cshr-net

  test:
    image: maven:3.5-jdk-8
    working_dir: "/usr/src/app"
    volumes:
      - "~/.m2:/root/.m2"
      - "./:/usr/src/app"
    command: "mvn test"
    networks:
      - cshr-net

networks:
  cshr-net:
    external: true
