spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cshr
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate # validate schema on run.  Updates handled by Liquibase.
    properties:
        hibernate:
            search:
                default:
                    directory_provider: filesystem
                    indexBase: /app/target/indexpath
  location:
    service:
      url: http://localhost:8989/findlocation/{searchTerm} # will be overridden by an env variable
      username: username
      password: password
  security:
    search_username: searchusername
    search_password: searchpassword
    crud_username: crudusername
    crud_password: crudpassword
    notify_username: notifyusername
    notify_password: notifypassword
  notifyservice:
    templateid:
    notifyApiKey: 
    accountEnableURL: http://localhost:3000/verifyemail/%s
  cshrAuthenticationService:
    secret: f0fb2106-a5c6-4b06-9300-e954a31efcf9
server:
  port: 8080
liquibase:
    enabled: false
    change-log: classpath:/changelog.xml
