
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/cshr
    url: jdbc:h2:mem:USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update # update schema on run. Use "create-drop" to reset schema on every run
server:
  port: 8080
