spring:
  datasource:
    url: jdbc:postgresql://db:5432/cshr
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update # update schema on run. Use "create-drop" to reset schema on every run
  location:
    service:
      url: http://localhost:8081/findlocation/{searchTerm} # will be overridden by an env variable
server:
  port: 8080
