spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cshr
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate # validate schema on run.  Updates handled by Liquibase.
  location:
    service:
      url: http://localhost:8989/findlocation/{searchTerm} # will be overridden by an env variable
server:
  port: 8080
liquibase:
    enabled: true
    change-log: classpath:/changelog.xml
